### ISSUE TITLE
tiapp.xml pointing ti non-existent appicon.png

### ISSUE THREAD

**Issue by kosso** [appcelerator/hyperloop-examples#18]
After importing the hyperloop-examples app project, Studio will immediately complain about there being no Default App Icon.  

tiapp.xml appears to point to appicon.png which does not exist. 

Shouldn't this be `<icon>DefaultIcon.png</icon>` instead?

When trying to stop Studio complaining, and selecting the DefaultIcon.png in the project root, inspecting the tiapp.xml after that shows duplicate xml elements for `<icon>` 

Environment: 
```
OS X     : 10.10.5
XCode   : 7.2.1
Studio 4.5.0.201602170821
node -v  : v0.12.7
TiSDK    : 5.2.0.GA 
ti -v    : 5.0.6
appc -v  : 5.2.0
hyperloop: 1.1.0 
```

**Comment by hansemannn** [comment]
That's a general issue with the Studio, which needs to do the required business logic to search for the appropriate icon in the project root (not only in the Resources). There is a JIRA-ticket for that, although I can't find it right now.
