### ISSUE TITLE
Main Hyperloop page downloads still points to 1.1.0 Beta

### ISSUE THREAD

**Issue by kosso** [appcelerator/hyperloop-examples#22]
The main download link on the [page](https://labs.appcelerator.com/project/55f74a9f421c44837717716b/Hyperloop-Module) about Hyperloop still points to the 1.1.0 Beta version. 

Should this now be version 1.1.2?

I'm building an app which is currently stretching the limits of my ObjectiveC to try and build some modules to implement a few UI things, and I'd love to be able to implement things directly via JS in a 'future way' sooner rather than later if possible. 

Thanks!

**Comment by hansemannn** [comment]
Closing, should point to latest since a few weeks.

**Comment by kosso** [comment]
Thanks! So, when #26 gets merged, will the link on https://labs.appcelerator.com/project/55f74a9f421c44837717716b/Hyperloop-Module change to 1.2.0?

**Comment by hansemannn** [comment]
They are curated independently, but labs will also be updated over the day. The PR will be merged today evening (europe time).

**Comment by kosso** [comment]
👍  Thanks Hans!
