### ISSUE TITLE
Error installing via gittio

### ISSUE THREAD

**Issue by sobytes** [appcelerator/hyperloop-examples#32]
Hi All,

When i try and install via gittio i get this message.

~~~
[INFO]  hyperloop searching...
[ERROR] hyperloop:commonjs no distributable available
[ERROR] hyperloop:android no distributable available
[ERROR] hyperloop:ios no distributable available
[ERROR] hyperloop:windows no distributable available
~~~

Any suggestions?

**Comment by sobytes** [comment]
I update the SDK gone now.
~~~
ti sdk install -b master -d
~~~

**Comment by hansemannn** [comment]
The hyperloop-module is not available on gittio. It can be installed using the [Appcelerator Labs](http://labs.appcelerator.com/project/55f74a9f421c44837717716b/Hyperloop-Module). Thanks! 🚀
