### ISSUE TITLE
CopySwiftLibs build/Products/Debug-iphoneos/Hyperloop_Sample.app

### ISSUE THREAD

**Issue by sobytes** [appcelerator/hyperloop-examples#47]
Hi All,

After upgrading to hyperloop and trying to run this project i get the following error.
~~~
CopySwiftLibs build/Products/Debug-iphoneos/Hyperloop_Sample.app
~~~

Any idea what might be causeing this.

I have xcode Version 7.3.1 (7D1014)
Appc Studio Appcelerator Studio, build: 4.7.0.201607250649
SDK 5.4.0.GA

Thanks

**Comment by sobytes** [comment]
Just as a update this only happens when trying to run on my device iphone6. It runs on the simulator?

**Comment by hansemannn** [comment]
@sobytes Please try Hyperloop 1.2.7 with 5.5.0.GA that was released yesterday. If that doesn't work, please file a [JIRA-ticket](https://jira.appcelerator.org) with an attached crash-log, thanks!
