### ISSUE TITLE
Error: Requested module not found

### ISSUE THREAD

**Issue by 1fabiopereira** [appcelerator/hyperloop-examples#56]
I make the setup as given in the documentation and always get the following error message: "Error: Requested module not found: android.app.Activity"

**Comment by hansemannn** [comment]
@1fabiopereira Which version of Hyperloop and the SDK do you use? SDK 6.0.4.GA and Hyperloop 2.1.0 should be fine though. Also, which example of this example-app throughs this error?

**Comment by 1fabiopereira** [comment]
I was having this problem in my own app and in all the examples of android I tested, I managed to do with it but in an ugly way and not even because this is happening but the module is only loaded if I call it twice Inside the same file the first time of the error and the second one works normally, if instead of call **require** I use the following function that created **hyperloopRequire**:

```
function hyperloopRequire(module){
	try {
		require(module);
	} catch(e){
		Ti.API.error(e);
	}
	return require(module);
};
```

**Comment by hansemannn** [comment]
We are trying to manage issues through [JIRA](http://jira.appcelerator.org), can you open an issue there? You are the first person having this error, so it has to be something with your environment. Ensure to attach all logs, test-apps and environments to the ticket. Thanks you!
