### ISSUE TITLE
Can't compile the app in iOS

### ISSUE THREAD

**Issue by guillefixx** [appcelerator/hyperloop-examples#59]
I'm trying to compile this example in two different Mac computers but it's not working on none of them. Both computers have the last version of cocoapods (1.2.1) and Titanium SDK 6.0.2.

This is what the console is showing on the **first computer**:
> [INFO] :   [Hyperloop] CocoaPods dependencies found. This will take a few moments but will be cached for subsequent builds
> [ERROR] :  An error occurred during build after 2s 979ms
> [ERROR] :  pod install returned a non-zero exit code

I tried to downgrade cocoapods to version 0.39.0 as some people suggested but i'm still getting the same error:
> [WARN] :   [Hyperloop] Using a CocoaPods version below 1.0.0 is deprecated. Please update your CocoaPods installation with: sudo gem install cocoapods
> [INFO] :   [Hyperloop] CocoaPods dependencies found. This will take a few moments but will be cached for subsequent builds
> [WARN] :   [Hyperloop] CocoaPods [!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.1`
> [ERROR] :  An error occurred during build after 18s 8ms
> [ERROR] :  pod install returned a non-zero exit code

This is what the console is showing on the **second computer**:

> [INFO] :   Processing JavaScript files
> [ERROR] :  An error occurred during build after 10s 614ms
> [ERROR] :  The iOS class "SKStoreReviewController" could not be found in the framework "StoreKit". (../build/iphone/build/Products/Debug-iphonesimulator/Hyperloop_Sample.app/ti.reviewdialog.js)

**Comment by hansemannn** [comment]
Hey there! The second error occurs because `SKStoreReviewController` is iOS 10.3 and later and is therefore only available when building with Xcode 8.3

The first one looks like a CocoaPods issue. Does it mention the exact CocoaPods error? Sometimes the Pod-dependencies are down, so that could also be an issue. Using CocoaPods 1.0.0 (I think 1.1.x is the most current one) are tested to be working.

**Comment by guillefixx** [comment]
Hey,

It's not mentioning the exact error, it's always showing this, even though I tried using cocoapods 1.0.0:
> [INFO] :   [Hyperloop] CocoaPods dependencies found. This will take a few moments but will be cached for subsequent builds
> [ERROR] :  An error occurred during build after 3s 778ms
> [ERROR] :  pod install returned a non-zero exit code

**Comment by hansemannn** [comment]
Try to create a new Hyperloop-based project, include the Podfile and exclude the Pods one by one. It has to be one of those. Also, please open a JIRA issue [here](jira.appcelerator.org) and include your exact environment, then we can pretty surely help you.

**Comment by anthonychung** [comment]
@hansemannn may need to add extra instructions in getting started guide for the example.

```
[sudo] gem install cocoapods
pod update
``` 
for people running cocoapods for the first time to enable them to run this example. 

Following error will occur when pod update is not run.
```
[ERROR] : pod install returned a non-zero exit code
```

**Comment by hansemannn** [comment]
@anthonychung Thanks for the suggestion! But I think it should not be required, since `pod install` is called internally. I didn't hear about the need to `pod update` manually in CocoaPods so far, but if it makes the difference, I am happy to add it to the instructions!

**Comment by anthonychung** [comment]
Perhaps it is just an issue that occurs with specific environments so just include as an accessible side note in case people run into trouble. 

Context of user experience...
Feedback from a user on slack said that this error had made them give up on hyperloop but said that running 'pod update' removed that error for them so they can try it again. 

Any side notes to help people new to set up appreciated.

**Comment by hansemannn** [comment]
Totally agree. Let me find some more background on why it works and we will try to do that internally, so the user doesn't need to do anything. Thx!
