### ISSUE TITLE
iBeacon example: Lack of "NSLocationAlwaysUsageDescription" into plist section of tiapp.xml and ranging

### ISSUE THREAD

**Issue by elettryxande** [appcelerator/hyperloop-examples#60]
For the use of iBeacon the hyperllop code call

locationManager.requestAlwaysAuthorization();

But the tiapp.xml file lack "NSLocationAlwaysUsageDescription".

"didRangeBeacons" delegation require use of "locationManager.startRangingBeaconsInRegion(region);"

**Comment by hansemannn** [comment]
Hey there! Can you file a PR for that? Thank you!

**Comment by hansemannn** [comment]
Fixed as part of https://github.com/appcelerator/hyperloop-examples/commit/1e7ca4f85f85d0dd4d978c6be5a9b26f9e3b98cb.
