### ISSUE TITLE
[ERROR] :  The iOS class "SKStoreReviewController" could not be found in the framework "StoreKit". (../build/iphone/assets/ti_reviewdialog_js)

### ISSUE THREAD

**Issue by yustein** [appcelerator/hyperloop-examples#61]
I'm getting the error

```
[ERROR] :  The iOS class "SKStoreReviewController" could not be found in the framework "StoreKit". (../build/iphone/assets/ti_reviewdialog_js)
```

during compiling

I'm using 6.1.2GA and 2.1.3

**Comment by hansemannn** [comment]
The `SKStoreReviewController` class is only available on iOS 10.3 and later. Did you try with Xcode 8.3?

**Comment by yustein** [comment]
That was exactly the case, thank you.

Suggestion: maybe put ios 11 as the minimum deployment target for the app?

**Comment by hansemannn** [comment]
Good suggestion! Can you file a PR? Will update it next week otherwise. Thanks again for raising this, I will close it then :-).
