### ISSUE TITLE
Script Error Couldn't find module: /hyperloop/uikit/uilabel for architecture: x86_64

### ISSUE THREAD

**Issue by snehalhumne** [appcelerator/hyperloop-examples#73]
Hi,
I am trying to run the hyperloop-examples on machine.
It gets compiled successfully but I am having a lot of runtime error.
Can you please help me on this one?

A configuration of Local Machine used.
Appc studio: 5.0.0.201712081732
TI SDK: 7.0.2
CLI: 7.0.2
hyperloop:3.0.2
Xcode: 9.0.1
Mac OS: High Sierra

This is happening on every list item displaying I have attached the screenshot for more info!
![simulator screen shot - iphone 6 - 2018-02-21 at 16 06 51](https://user-images.githubusercontent.com/20770912/36475615-452f6b58-1721-11e8-8dba-183728e22c2e.png)
![simulator screen shot - iphone 6 - 2018-02-21 at 16 06 54](https://user-images.githubusercontent.com/20770912/36475616-455bfd30-1721-11e8-85ae-5129deda6bb9.png)

Please let me know if I am missing anything!

Thanks.

**Comment by hansemannn** [comment]
Please do not run Hyperloop code with LiveView, that is not supported so far.
